config/routes.rb
Rails.application.routes.draw do
  root to:"tasks#index"
  
  get 'sessions/new'
  post 'sessions/create', to: "sessions#create"
  delete 'logout', to: 'sessions#destroy'
  get "signup", to: "users#new"
  
  resources :tasks
  
  resources :users, only:[:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :user
    validates  :status, presence:true, length:{maximum:10}
    validates  :content, presence:true, length:{maximum:10}
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email.downcase! }
    validates :name, presence:true, length:{maximum:50}
    validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
    has_many :tasks
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  private

  def require_user_logged_in
    unless logged_in?
      redirect_to sessions_new_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    
  end

  def create
     email = params[:session][:email].downcase
     password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to root_path
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
   private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
     before_action :require_user_logged_in
     before_action :correct_user, only:[:edit, :destroy, :show, :update]
     
    def index
      if logged_in?
        @task = Task.all
        @tasks = current_user.tasks.order(id: :desc)
      else
          redirect_to sessions_new_path
      end
    end
    
    def show
        @task = Task.find(params[:id])
    end
    
    def new
        @task = Task.new
    end
        
    def create
        @task = current_user.tasks.build(task_params)
        
        if @task.save
            flash[:success] = "新規タスクが作成されました"
            redirect_to @task
        else
            @tasks = current_user.tasks.order(id: :desc)
            flash.now[:dneger] = "新規タスクが作成できませんでした"
            render :new
        end
    end
        
    def edit
        @task = Task.find(params[:id])
    end
            
    def update 
        @task = Task.find(params[:id])
        
        if @task.update(task_params)
           flash[:success] = "タスクを編集しました"
           redirect_to @task
        else
           flash[:denger] = "タスクが編集できませんでした"
           render :new
        end
       
    end
                
    def destroy
        @task = Task.find(params[:id])
        @task.destroy
        
        flash[:success] = "タスクが削除されました"
        redirect_to tasks_url
    end
    
    private
    
    def task_params
        params.require(:task).permit(:content, :status,)
    end
    
    def correct_user
      @task = current_user.tasks.find_by(id: params[:id])
      unless @task
      redirect_to root_path
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show]
  
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = "ユーザを登録しました。"
      redirect_to root_path
    else
      flash.now[:denger] = "ユーザの登録に失敗しました。"
      render :new
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def correct_user
    @task = current_user.tasks.find_by(id: params[:id])
      unless @task
        redirect_to root_url
      end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_tasks.html.erb
<% flash.each do |message_type, message| %>
  <div><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<ul class="navbar-nav">
  <% unless logged_in? %>
        <li class="nav-item"><%= link_to 'Signup', signup_path, class: 'nav-link' %></li>
        <li class="nav-item"><%= link_to 'Login', sessions_new_path, class: 'nav-link' %></li>
  <% else %>        
        <li class="nav-item"><%= link_to 'Logout', logout_path, method: :delete %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tasklist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar"%>
     <%= render 'layouts/flash_tasks' %>
    <%= yield %>
  </body>
</html>

app/views/tasks/_error.html.erb
　<% if @task.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

app/views/tasks/edit.html.erb
<h1><%= @task.id %>の詳細ページ</h1>

<%= form_with(model:@task, local:true) do |f| %>
  <%= render 'error', task: @task%>
  
  <%= f.label :status, "ステータス"%>
  <%= f.text_field :status %>
  <%= f.label :content, "タスク"%>
  <%= f.text_field :content %>
  <%= f.submit "編集" %>
<% end %>

<%= link_to "タスク一覧", task_path %>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>
<ul>
  <% if logged_in? %>
    <% @tasks.each do |task| %>
      <li><%= link_to task.id, task %>:ステータス→<%= task.status %>::タスク→<%= task.content %></li>
    <% end %>
  <% end %>
  
</ul>
<%= link_to "新規タスクの作成", new_task_path %>

<div class="center jumbotron">
  <div class="text-center">
    <h1>Welcome to the Tasks</h1>
  </div>
</div>

app/views/tasks/new.html.erb
<h1>新規タスク作成</h1>

<%= form_with(model:@task, local:true) do |f| %>
  <%= render 'error', task: @task%>
  
  <%= f.label :status, "ステータス"%>
  <%= f.text_field :status %>
  <%= f.label :content, "タスク" %>
  <%= f.text_field :content %>
  <%= f.submit "投稿" %>
<% end %>
<%= link_to "一覧に戻る", tasks_path %>

app/views/tasks/show.html.erb
<h1>id:<%=@task.id%>のタスク詳細ページ</h1>
<p>タスク→<%= @task.content %></p>
<p>ステータス→<%= @task.status %></p>
<%= link_to "タスク一覧", tasks_path %>
<%= link_to "タスクの編集", edit_task_path(@task) %>
<%= link_to "タスクの削除", @task, method: :delete, data:{confirm: "本当に削除しますか？"} %>

app/views/users/_users.html.erb
<% if users.any? %>
  <ul class="list-unstyled">
    <% users.each do |user| %>
      <li class="media">
        <img class="mr-2 rounded" src="<%= gravatar_url(user, { size: 50 }) %>" alt="">
        <div class="media-body">
          <div>
            <%= user.name %>
          </div>
          <div>
            <p><%= link_to 'View profile', user_path(user) %></p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%= paginate users %>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<%= render 'users', users: @users %>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user, local: true) do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit 'Sign up', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1><%= @user.name%>さん、こんにちは！</h1>